### ISSUE TITLE
Add a feature extraction methods for models

### ISSUE THREAD

**Issue by SinaSarparast** [mila-aia/image_classification_simulation#44]
Many of the models we use for tasks like classification can also be used as feature extraction if the relevant layers of the model are extracted. A certain part of each model's architecture can be used for feature extraction like the latent layer of the AutoEncoders and all layers of ResNet except the final classification head. As a result, we need to consider this for each model based on its own structure. 

- [ ] I suggest developing a `extract_features ` method for each model class we have.

**Comment by alzaia** [comment]
Should we have the method on the base class and reimplement it then for each model? Or directly put it on each subclass model?
